### ISSUE TITLE
Improve and complete the radial visualization

### ISSUE THREAD

**Issue by raul-saez** [nearform/fastify-overview-ui#3]
Most of what was in this issue is complete, only missing [this](https://github.com/nearform/fastify-overview-ui/issues/3#issuecomment-1140231246).

Involve a designer from the team if needed.

**Comment by Eomm** [comment]
I think we should find a way to show the complete URL path for these cases (not the filesystem ones):

<img width="483" alt="image" src="https://user-images.githubusercontent.com/11404065/170821346-49488fb4-1eaa-4d2f-a139-65f9affd0267.png">

**Comment by raul-saez** [comment]
@Eomm Full path should be shown at the bottom left (If I remember correctly) of the screen when hovered, functionality is there so if you're not seeing it it might need looking into

**Comment by Eomm** [comment]
Yash, I can't see it actually:

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/11404065/170954337-71998f95-c29a-4996-b7fb-98a8e82e5009.png">

**Comment by Eomm** [comment]
I'm tracking my findings into this comment:
https://github.com/nearform/fastify-overview-ui/issues/3#issuecomment-1140231246

**Comment by simoneb** [comment]
Is there anything else to be done here?

**Comment by Eomm** [comment]
I would say these two optimizations: https://github.com/nearform/fastify-overview-ui/issues/3#issuecomment-1140231246

**Comment by Mazuh** [comment]
I'll work on this, I'm taking a look on the linked stuff.

**Comment by Mazuh** [comment]
@Eomm I pushed a branch there, can you take a look to confirm that this is what you meant?
