### ISSUE TITLE
Top buttons (theme and download)

### ISSUE THREAD

**Issue by Eomm** [nearform/fastify-overview-ui#9]
Testing the main branch, there are two buttons on the top bar:

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/11404065/170833174-1aa70ba8-6528-46b1-b1ae-ec97443f4e66.png">

those buttons do not execute any action.
I think the light/dark theme button is not useful at this stage, but the download button would be a valuable artefact that the user may download and include in any documentation.

Your thoughts?

**Comment by HassanBahati** [comment]
@Eomm does this mean it is handy  that we removed the light/dark theme button ?
